const data = {
    products:[
        {
            _id: '1',
            name: 'Almayas casual shirts',
            category: 'Shirts',
            image: '/images/p1.jpg',
            price: 1200,
            brand: 'Almayas',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '2',
            name: 'Almayas casual shirts for summar',
            category: 'Shirts',
            image: '/images/p2.jpg',
            price: 1000,
            brand: 'Almayas',
            rating: 2.5,
            numReviews: 3,
            description: 'high quality product',
        },
        {
            _id: '3',
            name: 'Almayas casual shirts fine fabric',
            category: 'Shirts',
            image: '/images/p3.jpg',
            price: 1100,
            brand: 'Almayas',
            rating: 3.5,
            numReviews: 18,
            description: 'high quality product',
        },
        {
            _id: '4',
            name: 'Almayas casual shirts for men',
            category: 'Shirts',
            image: '/images/p4.jpg',
            price: 1300,
            brand: 'Almayas',
            rating: 4.0,
            numReviews: 8,
            description: 'high quality product',
        },
        {
            _id: '5',
            name: 'Almayas casual shirts fine fashion',
            category: 'Shirts',
            image: '/images/p5.jpg',
            price: 1200,
            brand: 'Almayas',
            rating: 4.0,
            numReviews: 14,
            description: 'high quality product',
        },
    ],
};

export default data;